source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SWAnimatedTabBarControllerExample' do
    pod "SWAnimatedTabBarController", :path => "../"
end

#pod "SWAnimatedTabBarController", git: 'https://github.com/sarunw/SWAnimatedTabBarController'